# Generated by Django 3.1 on 2020-12-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20201224_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mixin',
            new_name='product',
        ),
    ]
