# Generated by Django 3.1 on 2021-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='signinm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=500)),
                ('password1', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=5000)),
            ],
        ),
    ]
