# Generated by Django 3.2.4 on 2021-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_id',
            field=models.IntegerField(),
        ),
    ]
